module.exports = {
    titles: {
        index: 'Ana Sayfa',
        register: 'Yeni Kullanıcı',
        login: 'Oturum aç',
        profile: 'Profilim',
        profileInfo: 'Kişisel Bilgiler',
        orders: 'Siparişlerim',
    },
    search: 'Ürün ara',
    navTop: {
        customerServices: 'Müşteri Hizmetleri',
        logout: 'Çıkış Yap',
        login: 'Oturum Aç',
        profile: 'Profilim',
        favorites: 'Favorilerim',
        cart: 'Alışveriş Sepetim',
    },
    footer: {
        corp: 'Kurumsal',
        social: 'Sosyal',
        mailList: 'E-Bülten',
    },
    address: {
        title: 'Adres başlığı',
        country: 'Ülke',
        city: 'Şehir',
        state: 'İlçe',
        postal: 'Posta Kodu',
        desc: 'Adres açıklaması',
        submit: 'Adres Ekle',
        fail: 'Yeni adres eklerken boş bir alan bırakmamalısınız.',
        success: 'Yeni bir adres eklendi.',
        saved: 'Adres Defteriniz',
        empty: 'Henüz bir adres eklemediniz.',
    },
    profile: {
        mail: 'E-Mail',
        phone: 'Telefon Numarası',
        cart: 'Alışveriş Sepetim',
        favs: 'Favorilerim',
    },
    orderDetails: {
        product: 'Ürün adı',
        amount: 'Adet',
        cost: 'Fiyat',
        total: 'Toplam',
        back: 'Geri',
    },
    orders: {
        order: 'Sipariş Numarası',
        date: 'Sipariş Tarihi',
        amount: 'Ürün Adedi',
    },
    profileInfo: {
        mail: 'E-Mail adresi değiştirilemez.',
        name: 'Adınız',
        surname: 'Soyadınız',
        idNumber: 'Kimlik Numarası',
        idPlaceholder: '11 haneli kimlik numaranızı ya da pasaport numaranızı giriniz..',
        area: 'Alan kodu',
        phone: 'Telefon numarası',
        phonePlaceholder: 'Telefon numaranızı giriniz',
        sex: 'Cinsiyet',
        male: 'Erkek',
        female: 'Kadın',
        country: 'Ülke',
        phoneFail: 'Telefon numarası ve kimlik numaranız rakamlardan oluşmalıdır.',
        nameFail: 'Adınız ve soyadınız 32 karakterden daha uzun olamaz.',
        removeAcc: 'Hesabı kaldır',
        removeAccDetail: 'Zalina hesabını silmek mi istiyorsunuz? O halde tıklayın!',
        changePass: 'Parola değiştir',
        changePassDetail: 'Parolanızı mı değiştirmek istiyorsunuz? Tıklayın!',
        logout: 'Oturumu kapat',
        logoutDetail: 'Aşağıda bulunan butona tıklayarak çıkış yapabilirsiniz! Güle güle!',
        update: 'Güncelle',
    },
    cart: {
        title: 'ALIŞVERİŞ SEPETİ',
        size: 'Beden',
        color: 'Renk',
        total: 'Toplam',
        cartTotal: 'Alışveriş sepeti toplamı',
        final: 'Sipariş değeri',
        empty: 'Alışveriş sepetiniz boş!',
        emptyDetail: 'Alışveriş sepetinize ürün kaydetmek veya daha önce kaydedilmiş ürünlere erişmek için oturum açın.',
        submit: 'Siparişi tamamla',
    }
}
