module.exports = {
    titles: {
        index: 'Home',
        register: 'New Account',
        login: 'Login',
        profile: 'Profile',
        profileInfo: 'Personal Information',
        orders: 'Orders',
    },
    search: 'Search for the products',
    navTop: {
        logout: 'Log Out',
        login: 'Login',
        profile: 'Profile',
        favorites: 'Favorite',
        cart: 'Shopping Cart',
        aboutus: 'About-Us',
    },
    footer: {
        corp: 'Corporate',
        social: 'Social',
        mailList: 'News',
    },
    address: {
        title: 'Address',
        country: 'Country',
        city: 'City',
        state: 'State',
        postal: 'Postal Code',
        desc: 'Adress Explanation',
        submit: 'Add Address',
        fail: 'You left empty fields.',
        success: 'A new address has been added.',
        saved: 'Address Book',
        empty: 'You have not added any address yet.',
    },
    profile: {
        mail: 'E-Mail',
        phone: 'Phone Number',
        cart: 'Shopping Basket',
        favs: 'Favorites',
    },
    orderDetails: {
        product: 'Product name',
        amount: 'Amount',
        cost: 'Price',
        total: 'Total',
        back: 'Go back',
    },
    orders: {
        order: 'Order Number',
        date: 'Order Date',
        amount: 'Product Amount',
    },
    profileInfo: {
        mail: 'E-mail address cannot be changed.',
        name: 'Your name',
        surname: 'Your last name',
        idNumber: 'Identification Number',
        idPlaceholder: 'Enter your 11-digit identification number or your passport number ..',
        area: 'Area Code',
        phone: 'Phone number',
        phonePlaceholder: 'Enter your phone number',
        sex: 'Gender',
        male: 'Male',
        female: 'Female',
        country: 'Country',
        phoneFail: 'Your phone number and ID number must consist of digits.',
        nameFail: 'Your name and surname cannot be longer than 32 characters.',
        removeAcc: 'Remove account',
        removeAccDetail: 'Do you want to delete Zalina account? Then click! ',
        changePass: 'Change password',
        changePassDetail: 'Do you want to change your password? Click! ',
        logout: 'Logout',
        logoutDetail: 'You can log out by clicking the button below! Good bye!',
        update: 'Update',
    },
    cart: {
        title: 'YOUR CART',
        size: 'Size',
        color: 'Color',
        total: 'Total',
        cartTotal: 'Cart Total',
        final: 'Product Price',
        empty: 'Shopping cart is empty.',
        emptyDetail: 'Sign in to save items in your shopping cart or access previously saved items.',
        submit: 'Complete the order',   
    }
}
